### ISSUE TITLE
Cannot find module 'rsvp' when installing addon.

### ISSUE THREAD

**Issue by icyrizard** [ember-cli-deploy/ember-cli-deploy-ssh-tunnel#9]
I get the error `Cannot find module 'rsvp'` when doing `ember install ember-cli-deploy-ssh-tunnel`. 

Now I know this can be an npm related issue as I've seen here https://github.com/ember-cli/ember-cli/issues/3714 but the problem keeps persisting after all the suggested fixes, i.e., `rm -rf node_modules && npm cache clear && npm install`.

**The exception trace:**
~~~javascript
Cannot find module 'rsvp'
Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/richard/Work/srxp/setup/srxp/webapp/node_modules/ember-cli-deploy-ssh-tunnel/index.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
~~~

In any case, I needed to install **RSVP**  package separately (`https://www.npmjs.com/package/rsvp`) to solve this issue. Therefore I naively conclude that the `ember-cli-deploy-ssh-tunnel` package is missing this dependency. I don't see another way of performing `require('rsvp')` successfully if the rsvp package is not directly installed... but I could be wrong.

OS version: Mac OS Mojave 10.14 (18A391)
Ember-cli: 2.5.1
npm: 2.15.11
node: 4.8.6

**Comment by lukemelia** [comment]
Should be fixed at this point.
